
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WINDOWS
 */
public class FormPeminjaman extends javax.swing.JFrame {


    /**
     * Creates new form FormPeminjaman
     */
    public FormPeminjaman() {
        initComponents();
        tampilkan_data_alat();
        tampilkan_data_peminjaman();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAlat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idAlat = new javax.swing.JTextField();
        namaalat = new javax.swing.JTextField();
        cbKondisi = new javax.swing.JComboBox<>();
        SimpanAlat = new javax.swing.JButton();
        HapusAlat = new javax.swing.JButton();
        ResetAlat = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelAlat = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cbJumlah = new javax.swing.JComboBox<>();
        buttonUpdate = new javax.swing.JButton();
        panelPeminjaman = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idalat = new javax.swing.JTextField();
        namapeminjam = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox<>();
        Ubah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjaman = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAlat.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("ID Alat               :");

        jLabel5.setText("Nama Alat         :");

        jLabel7.setText("Jumlah              :");

        idAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAlatActionPerformed(evt);
            }
        });

        cbKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak" }));

        SimpanAlat.setText("Simpan");
        SimpanAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanAlatActionPerformed(evt);
            }
        });

        HapusAlat.setText("Hapus");
        HapusAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusAlatActionPerformed(evt);
            }
        });

        ResetAlat.setText("Reset");
        ResetAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetAlatActionPerformed(evt);
            }
        });

        tabelAlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Alat", "Nama Alat", "Jumlah", "Kondisi"
            }
        ));
        tabelAlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAlatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelAlat);

        jLabel8.setText("Kondisi             :");

        cbJumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlatLayout = new javax.swing.GroupLayout(panelAlat);
        panelAlat.setLayout(panelAlatLayout);
        panelAlatLayout.setHorizontalGroup(
            panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlatLayout.createSequentialGroup()
                .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlatLayout.createSequentialGroup()
                        .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAlatLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAlatLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(buttonUpdate)
                                        .addComponent(jLabel8)))))
                        .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlatLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(idAlat, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(namaalat))
                                    .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbJumlah, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbKondisi, javax.swing.GroupLayout.Alignment.LEADING, 0, 191, Short.MAX_VALUE))))
                            .addGroup(panelAlatLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(SimpanAlat)
                                .addGap(53, 53, 53)
                                .addComponent(HapusAlat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResetAlat)
                                .addGap(33, 33, 33))))
                    .addGroup(panelAlatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlatLayout.setVerticalGroup(
            panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlatLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(namaalat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUpdate)
                    .addComponent(SimpanAlat)
                    .addComponent(HapusAlat)
                    .addComponent(ResetAlat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daftar Alat", panelAlat);

        panelPeminjaman.setBackground(new java.awt.Color(255, 255, 204));
        panelPeminjaman.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setText("ID Alat                        :");

        jLabel3.setText("Nama Peminjam          :");

        jLabel4.setText("Status                         :");

        idalat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idalatActionPerformed(evt);
            }
        });

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dipinjam", "Dikembalikan" }));
        cbstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstatusActionPerformed(evt);
            }
        });

        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });

        tabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Alat", "Nama Peminjam", "Status"
            }
        ));
        tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjaman);

        javax.swing.GroupLayout panelPeminjamanLayout = new javax.swing.GroupLayout(panelPeminjaman);
        panelPeminjaman.setLayout(panelPeminjamanLayout);
        panelPeminjamanLayout.setHorizontalGroup(
            panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Ubah)
                        .addGroup(panelPeminjamanLayout.createSequentialGroup()
                            .addGroup(panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(29, 29, 29)
                            .addGroup(panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idalat)
                                .addComponent(namapeminjam)
                                .addComponent(cbstatus, 0, 298, Short.MAX_VALUE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelPeminjamanLayout.setVerticalGroup(
            panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeminjamanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idalat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namapeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Ubah)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pengelolaan Peminjaman", panelPeminjaman);

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));
        jPanel1.setForeground(new java.awt.Color(204, 51, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("== SISTEM PEMINJAMAN ALAT LABORATORIUM ==");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void tampilkan_data_alat() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Alat");
    model.addColumn("Nama Alat");
    model.addColumn("Jumlah");
    model.addColumn("Kondisi");

    try {
        java.sql.Connection conn = Koneksi.getConnection();
        if (conn == null) {
            // Ini untuk menangani error "Koneksi ke database gagal (Object Null)" yang muncul di output Anda
            return;
        }

        String sql = "SELECT * FROM alat"; // Pastikan nama tabel di database adalah 'alat'
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), // Kolom ID Alat
                res.getString(2), // Kolom Nama Alat
                res.getString(3), // Kolom Jumlah
                res.getString(4)  // Kolom Kondisi
            });
        }
        
       
        tabelAlat.setModel(model);

    } catch (Exception e) {
        System.out.println("Error tampil alat: " + e.getMessage());
    }
}
   
 private void tampilkan_data_peminjaman() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Alat");
    model.addColumn("Nama Peminjam");
    model.addColumn("Status");

    try {
        String sql = "SELECT * FROM peminjaman";
        Connection conn = Koneksi.getConnection();
        
        if (conn == null) {
                System.out.println("Koneksi ke database gagal (Object Null)");
                return;
            }
        
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while(res.next()){
            model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3)});
        }
        tabelPeminjaman.setModel(model);
    } catch (Exception e) {
        System.out.println("Error : " + e.getMessage());
    }
}

    
    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
                                              
    String id = idalat.getText();
    String nama = namapeminjam.getText();
    String status = cbstatus.getSelectedItem().toString();

    // Validasi input agar tidak kosong
    if (id.isEmpty() || nama.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silakan pilih data yang akan diubah!");
    } else {
        try {
            // Memanggil koneksi
            Connection conn = Koneksi.getConnection();
            
            // Query SQL Update
            String sql = "UPDATE peminjaman SET nama_peminjam=?, status=? WHERE id_alat=?";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, status);
            pst.setString(3, id);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            
      
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal: " + e.getMessage());
        }
         tampilkan_data_peminjaman();
    }

    }//GEN-LAST:event_UbahActionPerformed

    private void idalatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idalatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idalatActionPerformed

    private void idAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAlatActionPerformed

    private void HapusAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusAlatActionPerformed
        // TODO add your handling code here:
                                           
    // 1. Ambil ID Alat dari inputan (ID didapat saat baris tabel diklik)
    String id = idAlat.getText();

    // 2. Validasi: Pastikan ada data yang dipilih
    if (id.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Pilih data pada tabel yang ingin dihapus!");
        return;
    }

    // 3. Konfirmasi penghapusan (Opsi Keamanan)
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(null, 
            "Apakah Anda yakin ingin menghapus data dengan ID " + id + "?", 
            "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        // 4. Panggil fungsi dari kelas Delete
        int hasil = Delete.hapusAlat(id);

        if (hasil > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            tampilkan_data_alat(); // Refresh tabel agar data hilang dari daftar
            
            // Bersihkan form setelah hapus
            idAlat.setText("");
            namaalat.setText("");
            cbJumlah.setSelectedIndex(0);
            cbKondisi.setSelectedIndex(0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal menghapus data.");
        }
    }

    }//GEN-LAST:event_HapusAlatActionPerformed

    private void cbstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbstatusActionPerformed

    private void tabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamanMouseClicked
        // TODO add your handling code here:
        
       int row = tabelPeminjaman.getSelectedRow();
       if (row == -1){
           return;
       }
       
       String id_alat = tabelPeminjaman.getValueAt(row, 0).toString();
       String nama_peminjam = tabelPeminjaman.getValueAt(row, 1).toString();
       String stts = tabelPeminjaman.getValueAt (row, 2).toString();
       
       idalat.setText(id_alat);
       namapeminjam.setText(nama_peminjam);
       cbstatus.setSelectedItem(stts);
       
   
    }//GEN-LAST:event_tabelPeminjamanMouseClicked

    private void tabelAlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAlatMouseClicked
        // TODO add your handling code here:
        
    int row = tabelAlat.getSelectedRow();
    if (row == -1){
        return;
    }
    
    // Pastikan menggunakan variabel 'tabelAlat', bukan 'tabelPeminjaman'
    String id_alat = tabelAlat.getValueAt(row, 0).toString();
    String nama_alat = tabelAlat.getValueAt(row, 1).toString();
    String jmlh = tabelAlat.getValueAt(row, 2).toString();
    String kondisi = tabelAlat.getValueAt(row, 3).toString();
    
    idAlat.setText(id_alat);
    namaalat.setText(nama_alat);
    cbJumlah.setSelectedItem(jmlh); // Perbaiki typo: setSelectedItem
    cbKondisi.setSelectedItem(kondisi);

    }//GEN-LAST:event_tabelAlatMouseClicked

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
                                                                              
                                     
    // 1. Ambil data dari inputan form
    String id = idAlat.getText(); // ID sebagai acuan (Primary Key)
    String nama = namaalat.getText();
    String jmlh = cbJumlah.getSelectedItem().toString();
    String knds = cbKondisi.getSelectedItem().toString();

    // Validasi sederhana: Pastikan ID tidak kosong
    if (id.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(null, "Pilih data pada tabel terlebih dahulu!");
        return;
    }

    // 2. Panggil fungsi dari kelas Update
    int hasil = Update.perbaruiDataAlat(id, nama, jmlh, knds);

    // 3. Cek apakah database berhasil diperbarui
    if (hasil > 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Data Alat Berhasil Diperbarui");
        tampilkan_data_alat(); // Refresh tabel agar data terbaru muncul
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal memperbarui data. ID tidak ditemukan.");
    }


    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void ResetAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetAlatActionPerformed
        // TODO add your handling code here:
        idAlat.setText(""); 
    namaalat.setText(""); 
    
    // Mengembalikan pilihan ComboBox ke posisi pertama
    cbJumlah.setSelectedIndex(0); 
    cbKondisi.setSelectedIndex(0);
    
    // Menaruh kursor di kotak Nama Alat agar siap mengetik lagi
    namaalat.requestFocus();

    }//GEN-LAST:event_ResetAlatActionPerformed

    private void SimpanAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanAlatActionPerformed
        // TODO add your handling code here:

        // 1. Ambil data selain ID karena ID sudah otomatis
        String nama = namaalat.getText();
        String jmlh = cbJumlah.getSelectedItem().toString();
        String knds = cbKondisi.getSelectedItem().toString();

        // 2. Validasi sederhana
        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Nama Alat tidak boleh kosong!");
            return;
        }

        // 3. Panggil fungsi Insert (tanpa mengirim parameter ID)
        int hasil = Insert.tambahAlat(nama, jmlh, knds);

        // 4. Cek hasil eksekusi
        if (hasil > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Data Alat Berhasil Disimpan");
            tampilkan_data_alat(); // Refresh tabel

            // Bersihkan form
            namaalat.setText("");
            idAlat.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal menyimpan data ke database.");
        }

    }//GEN-LAST:event_SimpanAlatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HapusAlat;
    private javax.swing.JButton ResetAlat;
    private javax.swing.JButton SimpanAlat;
    private javax.swing.JButton Ubah;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> cbJumlah;
    private javax.swing.JComboBox<String> cbKondisi;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JTextField idAlat;
    private javax.swing.JTextField idalat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField namaalat;
    private javax.swing.JTextField namapeminjam;
    private javax.swing.JPanel panelAlat;
    private javax.swing.JPanel panelPeminjaman;
    private javax.swing.JTable tabelAlat;
    private javax.swing.JTable tabelPeminjaman;
    // End of variables declaration//GEN-END:variables
}
